# See <https://pre-commit.com> for more information
# See <https://pre-commit.com/hooks.html> for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    - id: check-added-large-files

  - repo: https://github.com/realm/SwiftLint
    rev: 0.54.0
    hooks:
    - id: swiftlint
    language: swift
    types: [swift]
    entry: swiftlint --fix --strict --config .swiftlint.yml
    name: SwiftLint
    description: "Check Swift files for issues with SwiftLint"
    
